CREATE DATABASE SPRING_MVC_TRAINING_VER2;
USE SPRING_MVC_TRAINING_VER2;

CREATE TABLE MEMBER (
    MEMBER_ID 				VARCHAR(255) PRIMARY KEY,
    PASSWD 					VARCHAR(255) NOT NULL,
    PROFILE_ORIGINAL_NAME	VARCHAR(255) NOT NULL,
    PROFILE_UUID			VARCHAR(255) NOT NULL,
	MEMBER_NM 				VARCHAR(255) NOT NULL,
	SEX 					CHAR(1)  	 NOT NULL,
	BIRTH_AT 				DATE     	 NOT NULL, 
	HP 						VARCHAR(255) NOT NULL,
	SMSSTS_YN 				CHAR(1)   	 NOT NULL,
	EMAIL 					VARCHAR(255) NOT NULL,
	EMAILSTS_YN 			CHAR(1)   	 NOT NULL,
	ZIPCODE 				VARCHAR(255),
	ROAD_ADDRESS 			VARCHAR(255),
	JIBUN_ADDRESS 			VARCHAR(255),
	NAMUJI_ADDRESS 			VARCHAR(255),
	ETC 					VARCHAR(3000),
	JOIN_AT 				TIMESTAMP	DEFAULT NOW(),
	MODIFY_AT				TIMESTAMP	DEFAULT NOW()
);